name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
  pull_request:
    branches:
    - main
  schedule:
    - cron: "15 6 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo event trigger name
        run: |
          echo "Event name:  ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"

      - name: Files in repo using tree
        run: tree
