name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore:
    - .github/**
  pull_request:
    branches:
    - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment?
        type: environment
        required: true
        default: Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echoes
        run: |
          echo "Event name:  ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Files in repo using tree
        run: tree
